package constant

const (
	ORDER_PENDING   = "PENDING"
	ORDER_CREATED   = "CREATED"
	ORDER_PAID      = "PAID"
	ORDER_COMPLETED = "COMPLETED"
	ORDER_CANCEL    = "CANCEL"
	ORDER_REJECTED  = "REJECTED"
)
