// Code generated by mockery v2.39.1. DO NOT EDIT.

package repository

import (
	context "context"
	model "warehouse-service/model"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the IRepository type
type MockRepository struct {
	mock.Mock
}

// CreateTodo provides a mock function with given fields: ctx, customer
func (_m *MockRepository) CreateTodo(ctx context.Context, todo *model.Todo) error {
	ret := _m.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Todo) error); ok {
		r0 = rf(ctx, todo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
